version: '3.5' 

services: 
  frontend:
    image: frontend
    container_name: front
    ports:
      - 5000:5000

  backend:
    image: backend
    environment:
      - REDIS_HOST=red
      - POSTGRES_HOST=postgres_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 8080:8080
    container_name: back
    depends_on:
      - postgres

  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: red

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:


# Images "frontend" and "backend" had to be created first from the their respective Dockerfiles
# Command: dc up